from enum import Enum

import pytest

from dataclassio._example_schemas import Role, Team


# <generated by Gemini on 5/2/26>
class TestEnumSupport:
    """
    Tests the 'Integrity Phase' requirements for Enum handling in DataclassIO.
    """

    def test_from_dict_with_literal_value(self):
        """
        Test that from_dict correctly converts a raw string value
        to the corresponding Enum member.
        """
        data = {"team_name": "Engineering", "access_level": "admin"}
        team = Team.from_dict(data)

        assert isinstance(team.access_level, Role)
        assert team.access_level == Role.ADMIN

    def test_from_dict_with_enum_instance(self):
        """
        Test that from_dict handles cases where the input dictionary
        already contains Enum instances (internal data transfer).
        """
        data = {"team_name": "Design", "access_level": Role.EDITOR}
        team = Team.from_dict(data)

        assert team.access_level == Role.EDITOR

    def test_to_dict_always_exports_value(self):
        """
        Test that to_dict exports the Enum's .value representation
        to ensure JSON compatibility.
        """
        team = Team(team_name="Management", access_level=Role.VIEWER)
        exported_data = team.to_dict()

        # The result should be the raw value "viewer", not Role.VIEWER
        assert exported_data["access_level"] == "viewer"
        assert not isinstance(exported_data["access_level"], Enum)

    def test_from_dict_invalid_value_raises(self):
        """
        Verification that the generated code relies on the Enum's
        own instantiation logic for validation.
        """
        data = {"team_name": "Ghost", "access_level": "super_admin"}

        with pytest.raises(ValueError):
            Team.from_dict(data)
