from dataclasses import dataclass, field

from dataclassio import IOMixin


# ---------------------------------------------------------
# Dataclass Definitions
# ---------------------------------------------------------
@dataclass
class KWOnlyModel(IOMixin):
    """Tests that kw_only fields are passed explicitly, not positionally."""

    id: int
    name: str
    is_active: bool = field(kw_only=True, default=True)
    tags: list[str] = field(kw_only=True, default_factory=list)


@dataclass
class InitFalseModel(IOMixin):
    """Tests that init=False fields are excluded from the positional constructor call."""

    id: int
    internal_state: str = field(init=False)
    payload: str

    def __post_init__(self):
        self.internal_state = f"processed_{self.id}"


@dataclass
class BaseUser(IOMixin):
    """Parent class for inheritance testing."""

    id: int
    username: str
    metadata: dict = field(kw_only=True, default_factory=dict)


@dataclass
class AdminUser(BaseUser):
    """
    Child class for inheritance testing.
    Python ordering: id, username, access_level, then kw_only: metadata, privileges
    """

    access_level: int
    privileges: list[str] = field(kw_only=True, default_factory=list)


@dataclass
class CollisionModel(IOMixin):
    """
    Tests if the generator shadows its own internal variables.
    Internal vars to watch: 'dikt' (input), 'kls' (class), 'exc' (exception).
    """

    dikt: str
    kls: str
    exc: str
    id: int = 1


@dataclass
class FactoryCollision(IOMixin):
    dikt: list = field(default_factory=list)
    kls: dict = field(default_factory=dict)


@dataclass(kw_only=True)
class GlobalKWOnlyModel(IOMixin):
    """Tests that @dataclass(kw_only=True) forces all fields to be kwargs."""

    id: int
    category: str
    priority: int = 0


# ---------------------------------------------------------
# Test Class
# ---------------------------------------------------------
class TestPositionalCodegenEdgeCases:
    def test_kw_only_fields_passed_correctly(self):
        """
        Ensures that kw_only fields generate code like:
        cls(v_id, v_name, is_active=v_is_active, tags=v_tags)
        and NOT cls(v_id, v_name, v_is_active, v_tags)
        """
        input_data = {
            "id": 101,
            "name": "vision_model",
            "is_active": False,
            "tags": ["object_detection", "yolo"],
        }

        result = KWOnlyModel.from_dict(input_data)

        assert result.id == 101
        assert result.name == "vision_model"
        assert result.is_active is False
        assert result.tags == ["object_detection", "yolo"]

    def test_kw_only_fields_with_missing_defaults(self):
        """
        Ensures that kw_only fields successfully fall back to their defaults
        or default_factories if missing from the dictionary.
        """
        input_data = {
            "id": 102,
            "name": "language_model",
            # is_active and tags omitted
        }

        result = KWOnlyModel.from_dict(input_data)

        assert result.is_active is True
        assert result.tags == []

    def test_init_false_fields_are_ignored_in_constructor(self):
        """
        Ensures that fields with init=False do not break the positional argument
        mapping and are ignored during from_dict instantiation.
        """
        input_data = {
            "id": 404,
            "payload": "user_data",
            "internal_state": "should_be_ignored",  # This key should be ignored
        }

        result = InitFalseModel.from_dict(input_data)

        # The constructor should only receive id and payload.
        # internal_state should be generated by __post_init__.
        assert result.id == 404
        assert result.payload == "user_data"
        assert result.internal_state == "processed_404"

    def test_inheritance_field_ordering(self):
        """
        Ensures that subclass positional arguments are ordered correctly
        (Parent standard fields -> Child standard fields -> Parent kw_only -> Child kw_only).
        """
        input_data = {
            "id": 1,
            "username": "admin_root",
            "access_level": 5,
            "metadata": {"region": "us-east"},
            "privileges": ["read", "write", "delete"],
        }

        result = AdminUser.from_dict(input_data)

        assert result.id == 1
        assert result.username == "admin_root"
        assert result.access_level == 5
        assert result.metadata == {"region": "us-east"}
        assert result.privileges == ["read", "write", "delete"]

    def test_inheritance_missing_kw_only_defaults(self):
        """
        Ensures inherited models properly fall back to default_factories for kw_only fields.
        """
        input_data = {
            "id": 2,
            "username": "admin_limited",
            "access_level": 3,
            # metadata and privileges omitted
        }

        result = AdminUser.from_dict(input_data)

        assert result.id == 2
        assert result.metadata == {}
        assert result.privileges == []


class TestPositionalCodegenRobustness:
    def test_variable_name_collisions(self):
        """
        Ensures fields named 'dikt' or 'kls' do not break the generator logic.

        If the generator uses:
            v_dikt = dikt['dikt']
        It works.
        If the generator uses:
            dikt = dikt['dikt']
        It shadows the input dictionary and fails on the next field.
        """
        input_data = {
            "dikt": "dictionary_content",
            "kls": "class_identifier",
            "exc": "exception_message",
            "id": 99,
        }

        # This will trigger the generated from_dict logic
        result = CollisionModel.from_dict(input_data)

        assert result.dikt == "dictionary_content"
        assert result.kls == "class_identifier"
        assert result.exc == "exception_message"
        assert result.id == 99

    def test_class_level_kw_only_accuracy(self):
        """
        When @dataclass(kw_only=True) is used, the positional constructor
        kls(v_id, v_category, v_priority) is invalid.

        The generator must produce:
        kls(id=v_id, category=v_category, priority=v_priority)
        """
        input_data = {
            "id": 500,
            "category": "high_priority",
            # priority defaults to 0
        }

        result = GlobalKWOnlyModel.from_dict(input_data)

        assert result.id == 500
        assert result.category == "high_priority"
        assert result.priority == 0

    def test_collision_with_default_factory(self):
        """
        Ensures collisions are handled even when the field uses a factory.
        """

        # Test with empty input to trigger factories
        result = FactoryCollision.from_dict({})
        assert result.dikt == []
        assert result.kls == {}

        # Test with values
        result = FactoryCollision.from_dict({"dikt": [1, 2, 3], "kls": {"a": 1}})
        assert result.dikt == [1, 2, 3]
        assert result.kls == {"a": 1}
